# Versioning
foreman_ver: "3.12"
katello_ver: "4.14"

# Repository URLs
foreman_repo_url: "https://yum.theforeman.org/releases/{{ foreman_ver }}/el9/x86_64/foreman-release.rpm"
katello_repo_url: "https://yum.theforeman.org/katello/{{ katello_ver }}/katello/el9/x86_64/katello-release.rpm"

# Paths
safe_tmp_dir: "{{ ansible_user_dir }}/.ansible/tmp"

# Storage Configuration
foreman_pulp_vg: "vg_data"
foreman_pulp_lv: "lv_pulp"
foreman_pulp_size: "100%FREE"
foreman_pulp_mount: "/var/lib/pulp"

# Firewall Overrides
katello_required_ports:
  - { port: '443', proto: 'tcp', comment: 'HTTPS' }
  - { port: '5647', proto: 'tcp', comment: 'Qpid' }
  - { port: '8000', proto: 'tcp', comment: 'Pulp' }
  - { port: '9090', proto: 'tcp', comment: 'Smart Proxy' }