# Versioning
foreman_ver: "3.12"
katello_ver: "4.14"
puppet_ver: "7" # Puppet 7 is the standard for Foreman 3.12

# Repository URLs
foreman_repo_url: "https://yum.theforeman.org/releases/{{ foreman_ver }}/el9/x86_64/foreman-release.rpm"
katello_repo_url: "https://yum.theforeman.org/katello/{{ katello_ver }}/katello/el9/x86_64/katello-repos-latest.rpm"
puppet_repo_url: "https://yum.puppet.com/puppet{{ puppet_ver }}-release-el-9.noarch.rpm"

# Storage Configuration
foreman_pulp_vg: "vg_data"
foreman_pulp_lv: "lv_pulp"
foreman_pulp_size: "100%FREE"
foreman_pulp_mount: "/var/lib/pulp"
foreman_pulp_pvs: "/dev/sdb"

# RPM Cache
foreman_rpm_cache_dir: "/var/cache/foreman-katello"

# Firewall Overrides
katello_required_ports:
  - { port: '443', proto: 'tcp', comment: 'HTTPS' }
  - { port: '5647', proto: 'tcp', comment: 'Qpid' }
  - { port: '8000', proto: 'tcp', comment: 'Pulp' }
  - { port: '9090', proto: 'tcp', comment: 'Smart Proxy' }
