nodes:
  # Wazuh indexer nodes
  indexer:
    - name: wazuh-1
      ip: "10.0.40.207"
      dns:
        - "wazuh-1"
        - "wazuh-1.dmostlab.com"

  # Wazuh server nodes
  server:
    - name: wazuh-1
      ip: "10.0.40.207"
      dns:
        - "wazuh-1"
        - "wazuh-1.dmostlab.com"

  # Wazuh dashboard nodes
  dashboard:
    - name: wazuh-1
      ip: "10.0.40.207"
      dns:
        - "wazuh-1"
        - "wazuh-1.dmostlab.com"
